package com.projetEbilleterie.ebilleterie.domain.eticket2;

public enum TypePrice {
    INTERNAL_CHILD_PRICE,  EXTERNAL_CHILD_PRICE,
    INTERNAL_ADULT_PRICE, EXTERNAL_ADULT_PRICE,
    INTERNAL_UNIQUE_PRICE,EXTERNAL_UNIQUE_PRICE,
    RELATIVE_CHILD_PRICE, RELATIVE_ADULT_PRICE,
    RELATIVE_UNIQUE_PRICE
}
